name: Changelog

on:
  push:
    branches: main

jobs:
  Changelog:
    runs-on: ubuntu-latest
    name: Generate changelog
    steps:
      - uses: actions/checkout@v2
      
      - name: get short SHA
        id: vars
        run: |
         echo ::set-output name=sha_short::$(git rev-parse --short=4 ${{ github.sha }})

      - name: Generate Changelog
        id: changelog
        uses: mikeoconnor0308/action-github-changelog-generator@a38159e03b1574479a51359c29663d25291bd3e1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          headerLabel: "# Changelog"
          breakingLabel: "Breaking"
          enhancementLabel: "## Enhancements"
          bugsLabel: "Bug fixes"
          deprecatedLabel: '### Deprecations'
          removedLabel: "### Removals"
          securityLabel: "### Security"
          issuesLabel: "### 📁 Other issues"
          prLabel: "### 📁 Other issues"
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          author: true
          unreleased: true
          stripGeneratorNotice: true
          verbose: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          branch: changelog-autoupdate-${{ steps.vars.outputs.sha_short }}
          branch-suffix: timestamp
          title: Changelog Update
          commit-message: Update CHANGELOG.md
          token: ${{ secrets.GHA_ACCESS_TOKEN }}
          base: ${{ github.head_ref }}
