name: Changelog

on:
  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v2

      - id: changelog
        name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          author: true
          pullRequests: true
          issuesWoLabels: true
          prWoLabels: true
          unreleased: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: changelog-autoupdate
          branch-suffix: timestamp
          title: Changelog Auto-update
          commit-message: Update CHANGELOG.md
      #- name: Commit and push changelog
      #  run: |
      #    git config --local user.email github-action@entos.ai
      #    git config --local user.name github-action
      #    cat CHANGELOG.md
      #    git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && git push || echo "No changes to CHANGELOG.md"
